version: "3.8"
services:
    api:
        # image: thomas-oliver/nestjs-dockerized 
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://connect:NewV!s!0n@connect-insight-db-dev.postgres.database.azure.com:5432/postgres
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: connect
            POSTGRES_PASSWORD: NewV!s!0n
            POSTGRES_DB: postgres
